version: "3.9"

services:

  backend:
    build: .
    command: daphne vschools.asgi:application --port 8000 --bind 0.0.0.0 -v2
    volumes:
      - .:/code
    ports:
      - "8000:8000"

    networks:
      - net

networks:
  net:
    driver: bridge