# Generated by Django 3.2.3 on 2022-05-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_room_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_info',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
