# Generated by Django 3.2.3 on 2022-07-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_account_info_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_info',
            name='email_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
