# Generated by Django 3.2.3 on 2022-10-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_raised_hands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raised_hands',
            name='room',
        ),
        migrations.RemoveField(
            model_name='raised_hands',
            name='user',
        ),
        migrations.RemoveField(
            model_name='room_message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='room_message',
            name='user',
        ),
        migrations.AddField(
            model_name='room',
            name='time_limit',
            field=models.IntegerField(default=2400),
        ),
        migrations.DeleteModel(
            name='followings',
        ),
        migrations.DeleteModel(
            name='Raised_hands',
        ),
        migrations.DeleteModel(
            name='Room_message',
        ),
    ]
