# Generated by Django 3.2.3 on 2022-10-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_room_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_message',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
