# Generated by Django 3.2.3 on 2022-10-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_room_message_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='whiteboard_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.TextField()),
                ('file', models.FileField(upload_to='media')),
            ],
        ),
    ]
