# Generated by Django 3.2.3 on 2022-10-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_whiteboard_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_message',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
