# Generated by Django 3.2.3 on 2022-10-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_room_message_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_message',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
