# Generated by Django 3.2.3 on 2022-10-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20221025_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
