# Generated by Django 3.2.3 on 2022-10-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_room_message_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_message',
            name='file_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
